### ISSUE TITLE
Support modified files

### ISSUE THREAD

**Issue by zmb3** [fatih/gomodifytags#1]
It would be nice if this tool could accept modified files on stdin instead of requiring editors to save them off as temp files.

I would recommend using the same _archive_ format as `guru` and `gogetdoc`, which has a parser in  the [`go/buildutil` package](https://godoc.org/golang.org/x/tools/go/buildutil#ParseOverlayArchive).

The changes should be pretty straightforward:
- document the archive format in the readme
- add a `-modified` flag, and if present, use `buildutil.ParseOverlayArchive` to read the archive from stdin
- if the file is present in the archive, populate the `src` argument of [`parser.ParseFile`](https://godoc.org/go/parser#ParseFile)

With these updates, you'll be able to remove the temp files from vim-go and reuse the same code you already use for `guru` and `gogetdoc`.

I'm happy to take a stab at implementing these changes if you agree with the idea.

**Comment by fatih** [comment]
That sounds like a good plan Zac. Do it, I think it would be a valuable addition. To be honest, gomodifytags had a lot of features and I've didn't added it as I thought this can be added later :) Also in vim, right now I save the buffer first before passing it, so we could also get rid of it. Let me know if you start and thanks for bringing this up 👍
