### ISSUE TITLE
MP3 is converted to mp_3

### ISSUE THREAD

**Issue by campoy** [fatih/gomodifytags#10]
Hey,

I just ran this tool on a struct with field name `MP3` and the added tag was `json:"xmp_3,omitempty"`.

This is wrong, but I wonder if it's worth fixing at all.

**Comment by fatih** [comment]
Hey Francesc,

I've just tried it and it should work without any problems:

```shell
$ cat demo.go
package main

type Track struct {
	MP3 string
}
$ gomodifytags -file demo.go -struct Track -add-tags json
package main

type Track struct {
	MP3 string `json:"mp_3"`
}
$ gomodifytags -file demo.go -struct Track -add-tags json,xml
package main

type Track struct {
	MP3 string `json:"mp_3" xml:"mp_3"`
}
``` 

Not sure how you did get it ? We use https://github.com/fatih/camelcase for transforming the fields (which btw can be changed via the `-transform` flag as well)

**Comment by fatih** [comment]
Oh I see, your first comment has `xmp_3`, I think it's a typo. You're wondering why it's not `mp3` and is `mp_3` I guess :) That's how the camelcase package does it. For example `May5` or GL11Version`, these are transformed into `may_5` or `gl_11_version`.

**Comment by fatih** [comment]
I'm closing this as I don't see any problem. We also support static values for tags (you can specify which value should be used for a given key). I think from tens of fields, having one mismatched value is ok. People will argue which is correct or not, and going forward I think there is not much we can do anyway :)
