### ISSUE TITLE
Support for lisp-case transforms

### ISSUE THREAD

**Issue by urandom** [fatih/gomodifytags#20]
Hi,

Would it be possible to add support for lisp-case, where the words are separated by hyphens?

**Comment by fatih** [comment]
Hi @urandom 

Yeap it is. Can you give me an example struct with multiple fields and the expected struct with the struct tags in lisp mode ?

**Comment by urandom** [comment]
Hi,

Here's a real world example of mine:
```
type Config struct {
	Server      Server      `toml:"server"`
	DB          DB          `toml:"db"`
	Auth        Auth        `toml:"auth"`
	FeedParser  FeedParser  `toml:"feed-parser"`
	FeedManager FeedManager `toml:"feed-manager"`
	Content     Content     `toml:"content"`
}
```

I currently pretty much do a snake case insertion and then replace '_' with '-'

**Comment by fatih** [comment]
Great thanks. I'm going to tackle it this week. You'll be notified when this issue is closed.

**Comment by urandom** [comment]
Thanks

**Comment by fatih** [comment]
This is now merged to master. Thanks for the feedback.
