### ISSUE TITLE
support anonymous structs

### ISSUE THREAD

**Issue by brenol** [fatih/gomodifytags#24]
### Behavior

```go
package main

func main() {
    // I believe running :GoAddTags inside this anonymous struct should add its tags accordingly
	&struct {
		Hello string
	}{}
}
```

### Steps to reproduce:
- Open file .go file
- Create anonymous struct
- Run :GoAddTags in it
- Message "offset is not inside a struct" will show up

Will gladly work on this one if you have no problems with it.

**Comment by fatih** [comment]
Thanks for the feedback and sorry for late action, just had some time. This is fixed now in master. Let me know if you find any cases that is not covered.
