### ISSUE TITLE
add option to add tags to all structs in file

### ISSUE THREAD

**Issue by buyology** [fatih/gomodifytags#29]
as of now you have to specify the name of each struct or know the position of each struct individually.

would be great to be able to bulk process a large file with multiple structs.

**Comment by fatih** [comment]
Hi @buyology Did you tried  `--line 1,100000` (just give a very large number). I think that would solve it. I don't believe there is a Go file larger then 100K long :)

**Comment by buyology** [comment]
ah, I tried that, but looked at some old output. sorry for the noise and thanks for a nice tool! 👍

**Comment by damianoneill** [comment]
@fatih great tool, would be good to document this option.  

Thanks,
Damian.
