### ISSUE TITLE
Case cannot be changed without removing tags first

### ISSUE THREAD

**Issue by zmb3** [fatih/gomodifytags#3]
For the input file `main.go`:
```
package main

type Foo struct {
	BarBash  string `json:"bar_bash"`
	BazBob   string `json:"baz_bob"`
	QuuxKing int    `json:"quux_king"`
}
```

The command `gomodifytags -file main.go -struct Foo -add-tags json -transform camelcase` returns the input unmodified, instead of changing the tags from snake_case to camelCase.

For reference, the same behavior does _not_ occur with the `-sort` option.  I can have an input file with `xml` and `json` tags (in that order), and invoke `gomodifytags` with `-add-tags xml,json -sort` and the order of the tags is updated as expected.

**Comment by fatih** [comment]
Thanks @zmb3. I'll look into this.

**Comment by zmb3** [comment]
Hey @fatih - it's a pretty easy fix (see https://github.com/zmb3/gomodifytags/commit/9cc0c1fa6d114698a592109f663b72b095e19032), but it seems you intentionally didn't code it up this way as there's a test (which is now broken) to make sure we leave existing tags alone.

Do we really need an `-override` flag?  This may make it more difficult for editors to integrate.

My opinion is that it's fine to overwrite existing tags.  In most cases, people will be using this with structs that don't have any field tags.  And in cases where they do have existing tags that they want to leave alone, they can use the `-line` option to exclude those lines.

**Comment by fatih** [comment]
Now that I see this, I know why I made it like this. Because sometimes the field names and the tag names might not the same. So you don't want to change existing keys, if they are there. When I started using this privately for couple of weeks I was annoyed of that. That's the reason it's enabled and I've added a comment that we should add a `--override` flag.
