### ISSUE TITLE
Support Emacs

### ISSUE THREAD

**Issue by brantou** [fatih/gomodifytags#30]
I create an emacs-plugin named [emacs-go-tag](https://github.com/brantou/emacs-go-tag).
This package builds on[gomodifytags](https://github.com/fatih/gomodifytags) and is used to edit field tags for golang struct fields.
This package is inspired by **GoAddTags** of [vim-go](https://github.com/fatih/vim-go) and [go-add-tags](https://github.com/syohex/emacs-go-add-tags).
![image](https://user-images.githubusercontent.com/26197076/33465938-b0027a10-d685-11e7-9dc5-09a4fe84a17e.png)
![image](https://user-images.githubusercontent.com/26197076/33465949-ba9b67c0-d685-11e7-87f0-aba6e3e01815.png)

**Comment by fatih** [comment]
Nice! Can you open a pull request to the Readme and add you to the list? Thanks

**Comment by brantou** [comment]
👌，Thank you! #31

**Comment by brantou** [comment]
@fatih I was inspired by [The ultimate guide to writing a Go tool](https://arslan.io/2017/09/14/the-ultimate-guide-to-writing-a-go-tool/), thank you.
