### ISSUE TITLE
Different tags use different transforms

### ISSUE THREAD

**Issue by zhaogaolong** [fatih/gomodifytags#42]
A tag on a struct uses the same transforms, and I want to use separate transforms for each tag.

```go
AppDeploymentServerModuleConfig struct {
		ID                    int    `json:"id" gorm:"id"`
		AppDeploymentConfigID int    `json:"appDeploymentConfigID" gorm:"app_deployment_config_id"`

}
```
json use camelcase transforms, gorm use snakecase transforms

**Comment by fatih** [comment]
Hi @zhaogaolong,

Thanks for the feedback. You can already do this via gomodifytag. Not sure which editor you use, but you can pass `--transform` indidvidually. Here is a demo:

```
$  cat demo.go
package main

type Foo struct {
        MyExample             int 
        AppDeploymentConfigID int 
}

$ gomodifytags -file demo.go -line 3,6 -add-tags json -transform camelcase -w
package main

type Foo struct {
        MyExample             int `json:"myExample"`
        AppDeploymentConfigID int `json:"appDeploymentConfigID"`
}

$ gomodifytags -file demo.go -line 3,6 -add-tags gorm -transform snakecase -w
package main

type Foo struct {
        MyExample             int `json:"myExample" gorm:"my_example"`
        AppDeploymentConfigID int `json:"appDeploymentConfigID" gorm:"app_deployment_config_id"`
}
```

Closing this because it's possible already. Let me know if this doesn't solve your problem. Thanks

**Comment by zhaogaolong** [comment]
Hi @fatih 
I know this two command can solve my problem，but i want  perfect solution like:
```shell
 gomodifytags -file demo.go -line 3,6 -add-tags json -transform camelcase  -add-tags gorm -transform snakecase -w
``` 
merge two commands . It feels better.

**Comment by fatih** [comment]
Hi @zhaogaolong 

The syntax you mentioned is not clear and open to errors. I don't want to extend it and complicate the tool. The current one approach is simple enough and does the work. Thanks again for your feedback.

**Comment by zhaogaolong** [comment]
Hi @fatih 
I know you meaning, have diffrent kind tag is ugly design and isn't clear. useing same kind tag well  be better. Thanks again.
