### ISSUE TITLE
support -field option

### ISSUE THREAD

**Issue by luxiao9999** [fatih/gomodifytags#51]
gomodifytags -file test.go -struct PostReviewProcess -field Id --add-tags gorm -w

We can specify the field option to support modifying the tag of the specific field of the structure？
in structSelection function： add codes  like below：

	// struct selects all lines inside a struct

	start := c.fset.Position(encStruct.Pos()).Line
	end := c.fset.Position(encStruct.End()).Line

	if c.fieldName!=""{
		for i:=0;i<len(encStruct.Fields.List);i++{
			f:=encStruct.Fields.List[i]
			if len(f.Names)>0{
				if f.Names[0].Name==c.fieldName{
					start=c.fset.Position(f.Pos()).Line
					end=start
					break
				}
			}
		}
	}

**Comment by fatih** [comment]
Hi @luxiao9999 

Thanks for the issue, but I wasn't able to understand what you mean? Could you give me a `before` and `after` code with the expected output? Thanks

**Comment by fatih** [comment]
Closing this due insufficient information. Please feel free to re-open again after prodiving more information.
