### ISSUE TITLE
How 2 add tag name before element name?

### ISSUE THREAD

**Issue by muruganremis** [fatih/gomodifytags#52]
I've struct name as below

type Server struct {
    Name        string `json:"name"`
     Port        int    `json:"port"`
}

I want to add the element  before name (Person:name) as like below

type Server struct {
    Name        string `json:"Person:name"`
     Port        int    `json:"port"`
}

Is it possible to add this option in this lib?

**Comment by fatih** [comment]
I don't think it's possible. Also I think there is a bug with the ` value` feature:

```sh
$ cat main.go
package main

type Server struct {
        Name string `json:"name"`
        Port int    `json:"port"`
}
$ gomodifytags -file main.go -line 4,4 --add-tags json:"Person=name" --override
package main

type Server struct {
        Name string `json:"Person=name"`
        Port int    `json:"port"`
}

# This fails 
$ gomodifytags -file main.go -line 4,4 --add-tags json:"Person:name" --override
package main

type Server struct {
        Name string `json:"name" json:Person:name:"name"`
        Port int    `json:"port"`
}
```

Have to look into it

**Comment by fatih** [comment]
This is now fixed with: https://github.com/fatih/gomodifytags/pull/56
