### ISSUE TITLE
Add option to support custom formats

### ISSUE THREAD

**Issue by eduhenke** [fatih/gomodifytags#59]
I would like to be able to customize the format of the outputted tag, like so:
Input:
```golang
type Foo struct {
  FooID int
}
```
What I want:
```golang
type Foo struct {
  FooID int `json:"fooId"`
}
```

If I use the camelcase option, the `FooID`, becomes, as expected, `fooID`, would there be any way to convert it to `fooId`?

**Comment by fatih** [comment]
Unfortunately there is no such transform. These are the [current transformations](https://github.com/fatih/gomodifytags#adding-tags--options) we use:

<img width="868" alt="Screenshot-2020-05-10-00 04 29@2x" src="https://user-images.githubusercontent.com/438920/81493050-dca49000-9251-11ea-8a74-21571df94d18.png">

I'm not sure how to fix your case without adding significant changes to the `transform` part. Making it customizable is also a lot of work as it would require me to implement something that needs to be generic and embeddable into Go. I think the best way for you is to use camelcase and then do a simple `sed` or `find/replace` with an editor to change them. 

Let me know if that helps you. Thanks again for your feedback.
