### ISSUE TITLE
Adding Title Case to the list of supported cases

### ISSUE THREAD

**Issue by anant-barlota** [fatih/gomodifytags#65]
Hi, I was wondering if we could add an additional option of 'Title Case'. I came across its usefulness while adding csv tags to my structs.

I've written a simple code fix for it, but I'm unable to push the branch to this repo. I would appreciate any feedback on this.

**Comment by fatih** [comment]
Hi @anant-barlota Can you give me an example of Title Case? Would `pascalcase` not be useful for you? Would be great to have some real world examples and see how it's being used.

> I've written a simple code fix for it, but I'm unable to push the branch to this repo. I would appreciate any feedback on this.

The way you do at GitHub is, you create a fork of this repository, i.e: `github.com/anant-barlota/gomodifytags`, create a branch and then push your changes to your own fork. Then you come to this repo and you can create a PR. Let me know if anything is not clear.

**Comment by anant-barlota** [comment]
> Hi @anant-barlota Can you give me an example of Title Case? Would pascalcase not be useful for you? Would be great to have some real world examples and see how it's being used.

So I'm using a csv marshaller, that takes my structs and uses the tags for the column names. So my tags are space seperated strings for better representation. So like PascalCase but space separated.

> The way you do at GitHub is, you create a fork of this repository, i.e: github.com/anant-barlota/gomodifytags, create a branch and then push your changes to your own fork. Then you come to this repo and you can create a PR. Let me know if anything is not clear.
Oh thanks, I've never contributed on GitHub so had no clue.

**Comment by fatih** [comment]
This is now fixed and merged with the release https://github.com/fatih/gomodifytags/releases/tag/v1.16.0
