### ISSUE TITLE
Support custom tag for selected field in struct

### ISSUE THREAD

**Issue by rezadhah** [fatih/gomodifytags#67]
Hi, first thank you for this great library. So i have special case like this, i want to generate custom tag in my Struct, but not all the field will have it. Example

```
type Pokemon struct {
	Name     string
	Age        int    `validate:min=5,max=10`
}
```
so on the example above, i only want field `Age` have the custom tag with value `validate:min=5,max=10`

Can we have this feature? Thank you for your attention

**Comment by fatih** [comment]
This is now fixed with #68. The `v1.7.0` release includes this change: https://github.com/fatih/gomodifytags/releases/tag/v1.7.0
