### ISSUE TITLE
Add a mechanism to prefix tags

### ISSUE THREAD

**Issue by perrito666** [fatih/gomodifytags#73]
Some libraries like [the gorm ORM](https://github.com/go-gorm/gorm) or
the [gaum SQL query builder](https://github.com/shiftleftsecurity/gaum)
use a prefix in the tag name (ie `gorm:"column:struct_field"`,
`gaum:"field_name=struct_field"`) to help ther Scanner/Valuer interact
with the sql library in go.

I proposed a way to do this [in this Pull Request](https://github.com/fatih/gomodifytags/pull/69)

**Comment by fatih** [comment]
Fixed with https://github.com/fatih/gomodifytags/pull/69
