### ISSUE TITLE
Formatting tag values $field not generated

### ISSUE THREAD

**Issue by kecci** [fatih/gomodifytags#76]
I'm trying to generate with formatting tag values with -template. And I got null $field.

script executed:
```
gomodifytags -file purchase.go -all -add-tags gorm --template "column:$field" -w
```

result:
```
type PurchaseModel struct {
        BaseField         `json:",inline" gorm:"column:"`
        Code              string `json:"code,omitempty" gorm:"column:"`
        RefOrderId        string `json:"ref_order_id,omitempty" gorm:"column:"`
        Date              string `json:"date,omitempty" gorm:"column:"`
        Status            string `json:"status,omitempty" gorm:"column:"`
        PaymentStatus     string `json:"payment_status,omitempty" gorm:"column:"`
        InvoiceNumber     string `json:"invoice_number,omitempty" gorm:"column:"`
        InvoiceDate       string `json:"invoice_date,omitempty" gorm:"column:"`
        InvoiceDueDate    string `json:"invoice_due_date,omitempty" gorm:"column:"`
        InvoiceTotalPrice string `json:"invoice_total_price,omitempty" gorm:"column:"`
}
```

result `gorm:"column:"`
should be `gorm:"column:code"`

please help,
Thanks

**Comment by cutety** [comment]
@kecci You can take a look at this https://github.com/cutety/gomodifytags，We've fixed this bug.

**Comment by cavebeavis** [comment]
FYI, (working on Linux, btw), change to single quotes like `'field_name=$field'` and it worked for me...

**Comment by fatih** [comment]
Hi, 

Yeah you need to change it to single quotes. 

There is a PR that fixes it: https://github.com/fatih/gomodifytags/pull/79, but It's a breaking change and merging it might break other people's existing workflows. I'm going to look whether we can introduce it in a backwards compatible way. 

Thanks for the feedback.

**Comment by cutety** [comment]
> Hi,
> 
> Yeah, you need to change it to single quotes.
> 
> There is a PR that fixes it: #79, but It's a breaking change, and merging it might break other people's existing workflows. I'm going to look at whether we can introduce it in a backward compatible way.
> 
> Thanks for the feedback.

Glad to know that this project is still under maintenance, thanks for your efforts :>

**Comment by fatih** [comment]
This is now fixed with https://github.com/fatih/gomodifytags/pull/85. We now use the new `{field}` keyword, which I think is less prone to shell interpretations. We still support the old-style `$field` keyword, so this new change doesn't break existing scripts.

**Comment by fatih** [comment]
The changes are now released with the version: https://github.com/fatih/gomodifytags/releases/tag/v1.14.0
