### ISSUE TITLE
Feature Reqest: silent output

### ISSUE THREAD

**Issue by kokizzu** [fatih/gomodifytags#84]
Currently even with `-w` flag the output still printed in stdout
it would be nice if there's a flag that print only when there's error

**Comment by fatih** [comment]
Hi @kokizzu 

What's the use case for silent output? I wanted `gomodifytags` to be active and telling what was happening to the user. I'm open to suggestions.

**Comment by fatih** [comment]
I see. I designed `gomodifytags` mostly to be used in interactive mode, but I understand that people also use it for scripting lately. Let's keep this open, I'll work on it.

**Comment by fatih** [comment]
Thanks for the feedback again @kokizzu 

I released a new version with https://github.com/fatih/gomodifytags/releases/tag/v1.15.0 which now includes the new `--quiet` flag, that you can use to suppress the results.

**Comment by kokizzu** [comment]
awesome :3 thank you!
