### ISSUE TITLE
copy tag value and options

### ISSUE THREAD

**Issue by caarlos0** [fatih/gomodifytags#93]
I wonder if its possible and I'm missing something, or if it is something that you might want to accept as a PR.

tl;dr: I want to copy all `yaml` tag options and names to `json`

so, in:

```go
package main

type Foo struct {
  Bar string `yaml:"bar,omitempty"`
}
```

out:

```go
package main

type Foo struct {
  Bar string `yaml:"bar,omitempty" json:"bar,omitempty"`
}
```

is there a good way to do that with the current gomodifytags version?

**Comment by fatih** [comment]
Hi @caarlos0 

So, currently you can specify multiple tags:

```
$ gomodifytags -file demo.go -struct Foo -add-tags json,yaml
```

This will add both `json` and `yaml` to your struct. 

However, this will not copy over the custom yaml tags. Like you need to make sure to also specify `omitempty`. Would this work for you?

We don't have a `copy` transformation. I'm not sure how usable it would be though. I try to keep `gomodifytags` tidy and clean. We have though a `--template` flag where you can use templating. Maybe we can use that for copying.

**Comment by caarlos0** [comment]
yeah, not exactly what I wanted, ended up with some replace regex... as its just one time it was OK enough :) 

Thanks for this great tool btw!

cheers
